package com.worldtv.iptvplayer.data.source

import java.net.URLEncoder

/**
 * Xtream Codes login. There is no official public spec for this API; endpoints and URL
 * patterns follow community references and what panels actually serve.
 */
class XtreamCredentials(server: String, val username: String, val password: String) {

    /** Normalised base URL: scheme added if missing, no trailing slash or pasted endpoint. */
    val baseUrl: String = normalise(server)

    companion object {
        fun normalise(server: String): String {
            var s = server.trim()
            if (!s.startsWith("http://", ignoreCase = true) && !s.startsWith("https://", ignoreCase = true)) {
                s = "http://$s"
            }
            // People often paste a full get.php / player_api.php link.
            val lower = s.lowercase()
            for (suffix in listOf("/player_api.php", "/get.php", "/xmltv.php")) {
                val i = lower.indexOf(suffix)
                if (i > 0) s = s.substring(0, i)
            }
            return s.trimEnd('/')
        }

        /**
         * Recognises an M3U link generated by an Xtream panel
         * (http://host:port/get.php?username=U&password=P&type=m3u_plus...)
         * so the app can offer the richer API instead.
         */
        fun fromM3uUrl(url: String): XtreamCredentials? {
            val trimmed = url.trim()
            if (!trimmed.contains("get.php", ignoreCase = true)) return null
            val query = trimmed.substringAfter('?', "")
            if (query.isEmpty()) return null
            val params = query.split('&').associate {
                val k = it.substringBefore('=').lowercase()
                val v = java.net.URLDecoder.decode(it.substringAfter('=', ""), "UTF-8")
                k to v
            }
            val user = params["username"] ?: return null
            val pass = params["password"] ?: return null
            return XtreamCredentials(trimmed, user, pass)
        }
    }
}

/** Builds every URL the app needs from a login. */
class XtreamUrls(private val c: XtreamCredentials) {

    private val user get() = pathSegment(c.username)
    private val pass get() = pathSegment(c.password)

    fun api(action: String? = null, vararg params: Pair<String, String>): String {
        val sb = StringBuilder(c.baseUrl)
            .append("/player_api.php?username=").append(query(c.username))
            .append("&password=").append(query(c.password))
        if (action != null) sb.append("&action=").append(query(action))
        for ((k, v) in params) sb.append('&').append(query(k)).append('=').append(query(v))
        return sb.toString()
    }

    fun xmltv(): String =
        "${c.baseUrl}/xmltv.php?username=${query(c.username)}&password=${query(c.password)}"

    /** [ext] is "ts" or "m3u8"; the account's allowed_output_formats decides which works. */
    fun live(streamId: String, ext: String = "ts") = "${c.baseUrl}/live/$user/$pass/$streamId.$ext"

    fun movie(streamId: String, ext: String) = "${c.baseUrl}/movie/$user/$pass/$streamId.$ext"

    fun episode(episodeId: String, ext: String) = "${c.baseUrl}/series/$user/$pass/$episodeId.$ext"

    /**
     * Catch-up (timeshift). Pattern used by Xtream-compatible panels (community-documented):
     * /timeshift/{user}/{pass}/{durationMinutes}/{YYYY-MM-DD:HH-MM}/{streamId}.ts
     * [start] must be in the panel's own timezone (server_info.timezone).
     */
    fun timeshift(streamId: String, start: String, durationMinutes: Int, ext: String = "ts") =
        "${c.baseUrl}/timeshift/$user/$pass/$durationMinutes/$start/$streamId.$ext"

    private fun query(s: String) = URLEncoder.encode(s, "UTF-8")

    private fun pathSegment(s: String) = URLEncoder.encode(s, "UTF-8").replace("+", "%20")
}

/** Actions passed to player_api.php. */
object XtreamAction {
    const val LIVE_CATEGORIES = "get_live_categories"
    const val VOD_CATEGORIES = "get_vod_categories"
    const val SERIES_CATEGORIES = "get_series_categories"
    const val LIVE_STREAMS = "get_live_streams"
    const val VOD_STREAMS = "get_vod_streams"
    const val SERIES = "get_series"
    const val SERIES_INFO = "get_series_info"
    const val VOD_INFO = "get_vod_info"
    const val SHORT_EPG = "get_short_epg"
    const val SIMPLE_DATA_TABLE = "get_simple_data_table"
}
